name: Build Credentialing Status & Alerts API
approval_required: false
steps:
  - implement: /src/services/credentialing.service.ts
    goals:
      - Read PDC_provider_status; compute NETWORK_MISMATCH, EXPIRING_SOON, STALE_DATA, PENDING_EFFECTIVE
      - Filters: locations, carriers, status, issuesOnly
  - implement: /src/controllers/credentialing.controller.ts
    adds:
      - GET /api/credentialing/status
      - GET /api/credentialing/export.csv
  - tests: add /test/credentialing.spec.ts
  - run: ["npm run build","npm test"]
